import Foundation
import MongoSwift

/// The result of an `insertOne` command on a `RemoteMongoCollection`.
public struct RemoteInsertOneResult: Decodable {
    /// The identifier that was inserted. If the document doesn't have an identifier, this value
    /// will be generated by the Stitch server and added to the document before insertion.
    public let insertedId: ObjectId
    
    internal init(insertedId: ObjectId) {
        self.insertedId = insertedId
    }
}
