functions:
  "fetch_source":
    - command: git.get_project
      params:
        directory: "stitch-ios-sdk"
  "setup_swiftlint":
    - command: shell.exec
      params:
        shell: "bash"
        script: |
          git clone https://github.com/realm/SwiftLint
          cd SwiftLint
          git submodule update --init --recursive
          make install
  "setup_mongod":
    - command: shell.exec
      params:
        shell: "bash"
        script: |
          set -e
          curl --silent ${mongodb_url} | tar xz
    - command: shell.exec
      params:
        shell: "bash"
        background: true
        script: |
          set -e
          cd mongodb-*
          echo "starting mongod..."
          mkdir db_files
          ./bin/mongod --dbpath ./db_files --port 26000
    - command: shell.exec
      params:
        shell: "bash"
        script: |
          set -e
          cd mongodb-*
          echo "waiting for mongod to start up"
          ./bin/mongo --nodb --eval 'assert.soon(function(x){try{var d = new Mongo("localhost:26000"); return true}catch(e){return false}}, "timed out connecting")'
          echo "mongod is up."
  "setup_stitch":
    - command: shell.exec
      params:
        shell: "bash"
        silent: true
        script: |
          set -e
          echo export AWS_ACCESS_KEY_ID=${test_aws_key} >> creds
          echo export AWS_SECRET_ACCESS_KEY=${test_aws_secret} >> creds
    - command: shell.exec
      params:
        shell: "bash"
        script: |
          set -e
          echo "cloning stitch"
          mkdir -p src/github.com/10gen
          git clone git@github.com:10gen/stitch src/github.com/10gen/stitch
          echo "downloading update_doc"
          curl --silent -O "https://s3.amazonaws.com/stitch-artifacts/stitch-mongo-libs/stitch_mongo_libs_osx_patch_cbcbfd8ebefcca439ff2e4d99b022aedb0d61041_59e2b7a5c9ec4432c400181c_17_10_15_01_19_33/update_doc"
          echo "downloading assisted_agg"
          curl --silent -O "https://s3.amazonaws.com/stitch-artifacts/stitch-mongo-libs/stitch_mongo_libs_osx_patch_cbcbfd8ebefcca439ff2e4d99b022aedb0d61041_59e2b7ab2a60ed5647001827_17_10_15_01_19_39/assisted_agg"
          chmod +x update_doc
          chmod +x assisted_agg
          echo "building transpiler"
          cd src/github.com/10gen/stitch/etc/transpiler
          curl -O "https://nodejs.org/dist/v8.11.2/node-v8.11.2-darwin-x64.tar.gz"
          tar zxf node-v8.11.2-darwin-x64.tar.gz
          export PATH=`pwd`/node-v8.11.2-darwin-x64/bin/:$PATH
          rm -rf $HOME/.yarn
          curl -o- -L https://yarnpkg.com/install.sh | bash
          export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
          yarn install && yarn run build -t ${transpiler_target}
    - command: shell.exec
      params:
        shell: "bash"
        background: true
        script: |
          set -e
          curl --silent https://dl.google.com/go/go1.10.2.darwin-amd64.tar.gz | tar xz
          export GOROOT=`pwd`/go
          export PATH=$GOROOT/bin:$PATH
          export GOPATH=`pwd`
          export STITCH_PATH=$GOPATH/src/github.com/10gen/stitch
          export PATH="$PATH:$STITCH_PATH/etc/transpiler/bin"
          echo "running stitch"
          # TODO: Probably better to get an API key added to mimic cloud
          go run $STITCH_PATH/cmd/auth/user.go addUser -domainID 000000000000000000000000 -mongoURI mongodb://localhost:26000 -salt 'DQOWene1723baqD!_@#' -id "unique_user@domain.com" -password "password"
          go run $STITCH_PATH/cmd/server/main.go --configFile $STITCH_PATH/etc/configs/test_config.json
    - command: shell.exec
      params:
        shell: "bash"
        script: |
          counter=0
          until $(curl --output /dev/null --silent --head --fail http://localhost:9090); do
            echo "checking for API server to be up..."
            sleep 1
            let counter++
            if [ $counter -gt 100 ]; then
              exit 1
            fi
          done
  "setup_stitch_swift":
    - command: shell.exec
      params:
        shell: "bash"
        silent: true
        script: |
          set -e
          cd stitch-ios-sdk
          ./build.sh
          export DEVELOPER_DIR=/Applications/Xcode9.2.app
          export PATH=`pwd`/MobileSDKs/iphoneos/lib:$PATH
          export PATH=`pwd`/MobileSDKs/include/libbson-1.0/:$PATH
          export LD_LIBRARY_PATH=`pwd`/MobileSDKs/iphoneos/lib:$LD_LIBRARY_PATH
          export DYLD_LIBRARY_PATH=`pwd`/MobileSDKs/iphoneos/lib:$DYLD_LIBRARY_PATH
          git config --global user.email "evg@mongodb.com"
          git config --global user.name "evg"
          make
  "setup_test_creds":
    - command: shell.exec
      params:
        shell: "bash"
        silent: true
        script: |
          set -e
          cd stitch-ios-sdk
          sed -i -e 's/&lt;your-auth-token&gt;/${test_twilio_authtoken}/g' StitchCoreServicesTwilio-iOS/StitchCoreServicesTwilio-iOSTests/Info.plist
          sed -i -e 's/&lt;your-sid&gt;/${test_twilio_sid}/g' StitchCoreServicesTwilio-iOS/StitchCoreServicesTwilio-iOSTests/Info.plist
tasks:
  - name: lint
    commands:
      - func: "fetch_source"
      - func: "setup_swiftlint"
      - command: shell.exec
        params: 
          shell: "bash"
          script: |
            set -e
            cd stitch-ios-sdk/StitchCore
            swiftlint
  - name: run_core_tests
    commands:
      - func: "fetch_source"
      - func: "setup_stitch_swift"
      - command: shell.exec
        params: 
          shell: "bash"
          script: |
            set -e
            echo "running swift core tests"
            export DEVELOPER_DIR=/Applications/Xcode9.2.app
            cd stitch-ios-sdk
            make test
  - name: run_ios_tests
    commands:
      - func: "fetch_source"
      - func: "setup_mongod"
      - func: "setup_stitch"
      - func: "setup_stitch_swift"
      - func: "setup_test_creds"
      - command: shell.exec
        params:
          shell: "bash"
          script: |
            set -e
            export DEVELOPER_DIR=/Applications/Xcode9.2.app
            echo "running iOS tests"
            cd stitch-ios-sdk
            xattr -rc ~/Library/Developer/Xcode/DerivedData
            
            echo "!building StitchCore!"
            xcodebuild -workspace Stitch.xcworkspace/ -scheme StitchCore-Package -configuration Debug -derivedDataPath build -destination "platform=iOS Simulator,name=iPhone 7,OS=11.2"
            echo "!building StitchCoreAdminClient!"
            xcodebuild -workspace Stitch.xcworkspace/ -scheme StitchCoreAdminClient-Package -configuration Debug -derivedDataPath build -destination "platform=iOS Simulator,name=iPhone 7,OS=11.2"
            echo "!building StitchCoreTestUtils!"
            xcodebuild -workspace Stitch.xcworkspace/ -scheme StitchCoreTestUtils-Package -configuration Debug -derivedDataPath build -destination "platform=iOS Simulator,name=iPhone 7,OS=11.2"
            echo "!building StitchCoreServicesTwilio!"
            xcodebuild -workspace Stitch.xcworkspace/ -scheme StitchCoreServicesTwilio-Package -configuration Debug -derivedDataPath build -destination "platform=iOS Simulator,name=iPhone 7,OS=11.2"
            echo "!testing StitchCore-iOS!"
            xcodebuild test -workspace Stitch.xcworkspace/ -scheme StitchCore-iOS -configuration Debug -derivedDataPath build -destination "platform=iOS Simulator,name=iPhone 7,OS=11.2"
            echo "!testing StitchCoreServicesTwilio-iOS!"
            xcodebuild test -workspace Stitch.xcworkspace/ -scheme StitchCoreServicesTwilio-iOS -configuration Debug -derivedDataPath build -destination "platform=iOS Simulator,name=iPhone 7,OS=11.2"
buildvariants:
- name: macos-1013
  display_name: MacOS 1013
  run_on:
    - macos-1013
  expansions:
    mongodb_url: http://fastdl.mongodb.org/osx/mongodb-osx-ssl-x86_64-3.4.4.tgz
    transpiler_target: node8-macos
  tasks:
    - name: run_core_tests
    - name: run_ios_tests
