# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LocalMongoDBServiceExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StitchMDBKitExample
  pod 'MongoMobile', :git => 'ssh://git@github.com/10gen/swift-mongo-mobile', :branch => 'master'
  pod 'Toast-Swift', '~> 3.0.1'
end
