# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LocalMongoDBService' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StitchMDBKit
  pod 'MongoMobile', :git => 'ssh://git@github.com/10gen/swift-mongo-mobile', :branch => 'master'
end
