# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Stitch-PromiseKit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Stitch-PromiseKit
  pod "PromiseKit/CorePromise", "~> 6.0"
end

target 'Stitch_PromiseKitTests' do
  use_frameworks!

  pod "PromiseKit/CorePromise", "~> 6.0"
end
